name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Debug GHCR username
      #   run: |
      #     echo "=============================="
      #     if [ -z "${{ secrets.GHCR_USERNAME }}" ]; then
      #       echo "GHCR_USERNAME is EMPTY"
      #       exit 1
      #     else
      #       echo "GHCR_USERNAME is SET"
      #     fi
      #     echo "=============================="

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-ci:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-ci:${{ github.sha }}
      
      - name: Prepare EC2 key
        run: |
          echo "${{ secrets.EC2_KEY_B64 }}" | base64 --decode > ec2-key.pem
          chmod 400 ec2-key.pem
      
      - name: Deploy to AWS EC2
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          IMAGE="ghcr.io/$GHCR_USERNAME/fastapi-ci:latest"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_IP << EOF
            docker pull $IMAGE
            docker stop fastapi-ci || true
            docker rm fastapi-ci || true
            docker run -d --name fastapi-ci -p 8000:8000 $IMAGE
          EOF

